import type { Entity, NarrativeEvent, Tension, NarrativeArc } from '../graph/types.js';

// ==========================================
// THE OPENAI BOARD CRISIS — November 2023
// A perfect narrative with clear characters,
// escalating tensions, and dramatic resolution
// ==========================================

export const demoEntities: Entity[] = [
  {
    id: 'sam-altman',
    name: 'Sam Altman',
    type: 'person',
    motivation: 'Accelerate AI development and commercialization while maintaining OpenAI\'s mission',
    capability: 'CEO authority, industry connections, public influence, Silicon Valley network',
    alliances: ['greg-brockman', 'microsoft', 'openai-employees'],
    description: 'CEO of OpenAI, face of the AI revolution, visionary leader caught between safety and speed',
    firstSeen: '2023-11-01',
    lastSeen: '2023-11-29',
  },
  {
    id: 'openai-board',
    name: 'OpenAI Board of Directors',
    type: 'group',
    motivation: 'Ensure AI safety and adherence to OpenAI\'s non-profit mission',
    capability: 'Governance authority, power to hire/fire CEO, control of corporate structure',
    alliances: [],
    description: 'The governing body that prioritized safety concerns over commercial momentum',
    firstSeen: '2023-11-01',
    lastSeen: '2023-11-29',
  },
  {
    id: 'ilya-sutskever',
    name: 'Ilya Sutskever',
    type: 'person',
    motivation: 'AI safety and ensuring superintelligence benefits humanity',
    capability: 'Chief Scientist role, deep technical authority, board membership',
    alliances: ['openai-board'],
    description: 'Co-founder and Chief Scientist, torn between loyalty to Sam and safety convictions',
    firstSeen: '2023-11-01',
    lastSeen: '2023-11-29',
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    type: 'company',
    motivation: 'Protect $13B investment, maintain AI competitive advantage, integrate OpenAI tech',
    capability: 'Massive financial resources, Azure infrastructure, enterprise distribution',
    alliances: ['sam-altman'],
    description: 'The tech giant with billions at stake, blindsided by the board\'s move',
    firstSeen: '2023-11-01',
    lastSeen: '2023-11-29',
  },
  {
    id: 'satya-nadella',
    name: 'Satya Nadella',
    type: 'person',
    motivation: 'Protect Microsoft\'s AI investment and strategic position',
    capability: 'Microsoft CEO, vast corporate resources, hiring authority',
    alliances: ['microsoft', 'sam-altman'],
    description: 'Microsoft CEO who played a masterful chess game during the crisis',
    firstSeen: '2023-11-17',
    lastSeen: '2023-11-29',
  },
  {
    id: 'greg-brockman',
    name: 'Greg Brockman',
    type: 'person',
    motivation: 'Support Sam Altman, continue OpenAI\'s technical mission',
    capability: 'President role, technical leadership, co-founder status',
    alliances: ['sam-altman', 'openai-employees'],
    description: 'OpenAI President who resigned in solidarity with Altman',
    firstSeen: '2023-11-01',
    lastSeen: '2023-11-29',
  },
  {
    id: 'openai-employees',
    name: 'OpenAI Employees',
    type: 'group',
    motivation: 'Job security, continue working on cutting-edge AI, loyalty to leadership',
    capability: 'Collective bargaining power, irreplaceable talent, threat of mass exodus',
    alliances: ['sam-altman', 'greg-brockman'],
    description: '770+ employees who signed the letter demanding the board resign',
    firstSeen: '2023-11-01',
    lastSeen: '2023-11-29',
  },
  {
    id: 'emmett-shear',
    name: 'Emmett Shear',
    type: 'person',
    motivation: 'Stabilize OpenAI, investigate safety concerns, prove leadership capability',
    capability: 'Interim CEO authority, Twitch co-founder credibility',
    alliances: ['openai-board'],
    description: 'The interim CEO brought in to replace Altman, lasting barely 3 days',
    firstSeen: '2023-11-20',
    lastSeen: '2023-11-22',
  },
  {
    id: 'mira-murati',
    name: 'Mira Murati',
    type: 'person',
    motivation: 'Maintain OpenAI operations, bridge between factions',
    capability: 'CTO role, operational knowledge, respected by both sides',
    alliances: ['sam-altman', 'openai-employees'],
    description: 'CTO briefly named interim CEO, caught in the middle of the power struggle',
    firstSeen: '2023-11-17',
    lastSeen: '2023-11-29',
  },
];

export const demoEvents: NarrativeEvent[] = [
  {
    id: 'evt-firing',
    title: 'The Firing',
    description: 'The OpenAI board abruptly fires Sam Altman as CEO, citing he was "not consistently candid in his communications." The tech world is stunned.',
    timestamp: '2023-11-17T12:00:00Z',
    participants: ['sam-altman', 'openai-board', 'ilya-sutskever'],
    causalPredecessors: [],
    impact: 1.0,
    sentiment: -0.9,
  },
  {
    id: 'evt-brockman-resigns',
    title: 'Brockman Resigns',
    description: 'Greg Brockman resigns as OpenAI President in solidarity with Altman. The first domino falls.',
    timestamp: '2023-11-17T15:00:00Z',
    participants: ['greg-brockman', 'openai-board'],
    causalPredecessors: ['evt-firing'],
    impact: 0.7,
    sentiment: -0.7,
  },
  {
    id: 'evt-murati-interim',
    title: 'Murati Named Interim CEO',
    description: 'CTO Mira Murati is named interim CEO as the board scrambles to maintain stability.',
    timestamp: '2023-11-17T18:00:00Z',
    participants: ['mira-murati', 'openai-board'],
    causalPredecessors: ['evt-firing'],
    impact: 0.5,
    sentiment: -0.2,
  },
  {
    id: 'evt-microsoft-shock',
    title: 'Microsoft Blindsided',
    description: 'Microsoft, OpenAI\'s largest investor at $13B, learns of the firing minutes before the public announcement. Satya Nadella is reportedly furious.',
    timestamp: '2023-11-17T12:30:00Z',
    participants: ['microsoft', 'satya-nadella', 'openai-board'],
    causalPredecessors: ['evt-firing'],
    impact: 0.8,
    sentiment: -0.8,
  },
  {
    id: 'evt-negotiation-fails',
    title: 'Reinstatement Talks Collapse',
    description: 'Negotiations to bring Altman back fail as the board refuses to resign. The crisis deepens.',
    timestamp: '2023-11-19T20:00:00Z',
    participants: ['sam-altman', 'openai-board', 'microsoft'],
    causalPredecessors: ['evt-firing', 'evt-microsoft-shock'],
    impact: 0.7,
    sentiment: -0.6,
  },
  {
    id: 'evt-shear-appointed',
    title: 'Emmett Shear Named CEO',
    description: 'The board appoints Twitch co-founder Emmett Shear as interim CEO, signaling they won\'t back down.',
    timestamp: '2023-11-20T08:00:00Z',
    participants: ['emmett-shear', 'openai-board'],
    causalPredecessors: ['evt-negotiation-fails'],
    impact: 0.6,
    sentiment: -0.4,
  },
  {
    id: 'evt-microsoft-offer',
    title: 'Nadella\'s Chess Move',
    description: 'Satya Nadella announces Altman and Brockman will join Microsoft to lead a new advanced AI research team. A masterstroke of corporate strategy.',
    timestamp: '2023-11-20T10:00:00Z',
    participants: ['satya-nadella', 'sam-altman', 'greg-brockman', 'microsoft'],
    causalPredecessors: ['evt-negotiation-fails'],
    impact: 0.9,
    sentiment: 0.3,
  },
  {
    id: 'evt-employee-letter',
    title: 'The Employee Ultimatum',
    description: '770+ of OpenAI\'s 770 employees sign a letter demanding the board resign and reinstate Altman, threatening to follow him to Microsoft.',
    timestamp: '2023-11-20T18:00:00Z',
    participants: ['openai-employees', 'openai-board', 'sam-altman'],
    causalPredecessors: ['evt-microsoft-offer', 'evt-shear-appointed'],
    impact: 0.95,
    sentiment: -0.3,
  },
  {
    id: 'evt-ilya-regret',
    title: 'Ilya\'s Reversal',
    description: 'Ilya Sutskever signs the employee letter, tweeting "I deeply regret my participation in the board\'s actions." The safety faction fractures.',
    timestamp: '2023-11-20T20:00:00Z',
    participants: ['ilya-sutskever', 'openai-board', 'openai-employees'],
    causalPredecessors: ['evt-employee-letter'],
    impact: 0.8,
    sentiment: 0.2,
  },
  {
    id: 'evt-reinstatement',
    title: 'The Return of the King',
    description: 'Sam Altman returns as CEO with a new board including Bret Taylor and Larry Summers. The old board is dissolved. The five-day crisis ends.',
    timestamp: '2023-11-22T10:00:00Z',
    participants: ['sam-altman', 'openai-board', 'microsoft', 'openai-employees'],
    causalPredecessors: ['evt-employee-letter', 'evt-ilya-regret', 'evt-microsoft-offer'],
    impact: 1.0,
    sentiment: 0.8,
  },
];

export const demoTensions: Tension[] = [
  {
    id: 'tension-safety-vs-speed',
    name: 'Safety vs. Speed',
    description: 'The fundamental tension between the board\'s safety-first mandate and the commercial pressure to ship AI products rapidly. The board believed Altman was moving too fast.',
    parties: ['openai-board', 'sam-altman'],
    status: 'resolving',
    intensity: 0.9,
    duration: 14,
    relatedEvents: ['evt-firing', 'evt-negotiation-fails', 'evt-reinstatement'],
    validFrom: '2023-11-01',
    validTo: '2023-11-22',
  },
  {
    id: 'tension-governance-vs-talent',
    name: 'Governance vs. Talent',
    description: 'The board had legal authority but the employees had the actual power — without them, OpenAI is just a corporate shell. Governance without legitimacy proved hollow.',
    parties: ['openai-board', 'openai-employees'],
    status: 'resolved',
    intensity: 0.95,
    duration: 5,
    relatedEvents: ['evt-employee-letter', 'evt-reinstatement'],
    validFrom: '2023-11-17',
    validTo: '2023-11-22',
  },
  {
    id: 'tension-microsoft-influence',
    name: 'Microsoft\'s Gravitational Pull',
    description: 'Microsoft\'s $13B investment gave it enormous leverage. The threat of absorbing OpenAI\'s talent forced the board\'s hand, but raises questions about non-profit AI governance.',
    parties: ['microsoft', 'openai-board'],
    status: 'simmering',
    intensity: 0.7,
    duration: 30,
    relatedEvents: ['evt-microsoft-shock', 'evt-microsoft-offer', 'evt-reinstatement'],
    validFrom: '2023-11-01',
  },
  {
    id: 'tension-ilya-loyalty',
    name: 'Ilya\'s Divided Loyalty',
    description: 'Ilya Sutskever was torn between his genuine safety concerns and his loyalty to colleagues. His reversal was the emotional climax of the crisis.',
    parties: ['ilya-sutskever', 'sam-altman'],
    status: 'resolved',
    intensity: 0.85,
    duration: 3,
    relatedEvents: ['evt-firing', 'evt-ilya-regret'],
    validFrom: '2023-11-17',
    validTo: '2023-11-20',
  },
  {
    id: 'tension-nonprofit-vs-profit',
    name: 'Non-Profit Mission vs. For-Profit Reality',
    description: 'OpenAI\'s unusual structure — a non-profit board overseeing a capped-profit company — created a governance crisis. Can idealistic structures survive commercial success?',
    parties: ['openai-board', 'microsoft'],
    status: 'simmering',
    intensity: 0.6,
    duration: 30,
    relatedEvents: ['evt-firing', 'evt-reinstatement'],
    validFrom: '2023-11-01',
  },
];

export const demoArcs: NarrativeArc[] = [
  {
    id: 'arc-coup',
    name: 'The Boardroom Coup',
    description: 'A story of institutional overreach: a board tries to assert control and is overwhelmed by the forces they underestimated — talent loyalty, corporate power, and public narrative.',
    phase: 'resolution',
    characters: ['openai-board', 'sam-altman', 'openai-employees', 'microsoft'],
    events: ['evt-firing', 'evt-negotiation-fails', 'evt-shear-appointed', 'evt-employee-letter', 'evt-reinstatement'],
    tensions: ['tension-safety-vs-speed', 'tension-governance-vs-talent'],
    startDate: '2023-11-17',
    endDate: '2023-11-22',
  },
  {
    id: 'arc-microsoft-play',
    name: 'Microsoft\'s Power Play',
    description: 'Satya Nadella turned a crisis into an opportunity. By offering Altman a home at Microsoft, he created a win-win: either OpenAI returns Altman, or Microsoft gets the talent.',
    phase: 'resolution',
    characters: ['satya-nadella', 'microsoft', 'sam-altman', 'greg-brockman'],
    events: ['evt-microsoft-shock', 'evt-microsoft-offer', 'evt-reinstatement'],
    tensions: ['tension-microsoft-influence'],
    startDate: '2023-11-17',
    endDate: '2023-11-22',
  },
  {
    id: 'arc-safety-question',
    name: 'The Unresolved Safety Question',
    description: 'The deeper story beneath the drama: the board\'s safety concerns didn\'t disappear with their removal. The tension between AI safety and commercial velocity remains the defining question.',
    phase: 'rising_action',
    characters: ['ilya-sutskever', 'openai-board', 'sam-altman'],
    events: ['evt-firing', 'evt-ilya-regret', 'evt-reinstatement'],
    tensions: ['tension-safety-vs-speed', 'tension-nonprofit-vs-profit'],
    startDate: '2023-11-17',
  },
];
